name: Build and Release OpenWrt for Phicomm N1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget python3

    - name: Clone LEDE source
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Use your custom .config
      run: |
        cp configs/n1.config lede/.config

    - name: Build firmware
      run: |
        cd lede
        make defconfig
        make -j$(nproc)

    - name: Copy rootfs tarball
      run: |
        cp lede/bin/targets/armvirt/64/openwrt-armvirt-64-generic-rootfs.tar.gz ./openwrt_armvirt64.tar.gz

    - name: Run flippy's packit script for N1
      run: |
        sudo chmod +x mk_s905d_n1.sh
        sudo ./mk_s905d_n1.sh openwrt_armvirt64.tar.gz

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-n1-image
        path: out/openwrt_s905d_n1.img.gz

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        name: Phicomm N1 OpenWrt Firmware v1.0.0
        body: |
          This release contains the OpenWrt firmware image for Phicomm N1 (S905D) built via GitHub Actions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload firmware to Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/openwrt_s905d_n1.img.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
